### ISSUE TITLE
Incorrect converstion between count and dozen

### ISSUE THREAD

**Issue by emersonthis** [mhuggins/ruby-measurement#16] opened 2019-04-03 15:57 UTC
Great library!

I'm seeing unexpected results when trying to convert between `dozen` and `count` units. The conversion appears to happen correctly, but the original `quantity` property appears to be leftover. So if I convert `12 count` to `dozen` I end up with `12 doz`.

Example:

```
m = Measurement.parse("12 count") # 12 count
m.convert_to("dozen") # 1 doz
m.quantity # 12
```

**Comment by mhuggins** [comment] 2019-04-03 19:33
Thanks for the report!  I don't currently have the bandwidth to dig into a fix for this, but I'd happily accept a pull request. 😃

**Comment by emersonthis** [comment] 2019-04-07 14:30
I can take a crack. Probably in the next week or two.

**Comment by mhuggins** [comment] 2019-04-07 21:31
I just realized from your sample code what the issue is.  You need to assign the conversion to `m` again if you want to use it.  e.g.:

```ruby
m = Measurement.parse("12 count") # 12 count
m = m.convert_to("dozen") # 1 doz
m.quantity # 1
m.unit # doz
```

**Comment by emersonthis** [comment] 2019-04-08 01:09
Ahh. I thought that method modified the same instance. Thanks for clarifying.

**Comment by mhuggins** [comment] 2019-04-08 02:22
No problem!

**Closed by mhuggins** 2019-04-08 02:22 UTC
